

templates:

  defaults:
    proxy: 
      http: http://10.0.3.33:8888/
      https: http://10.0.3.33:8888/

    transmission:
      host: 10.0.3.33
      port: 9091
      path: /mnt/storage/contents/downloads
      ratio: 10

  music:
    proxy: 
      http: http://10.0.3.33:8888/
      https: http://10.0.3.33:8888/

    transmission:
      host: 10.0.3.33
      port: 9091
      path: /mnt/storage/contents/music
      ratio: 1

    regexp:
      reject: 
        - mp4
        - flac

  aviguy:
    if: 
      - "'AVIGUY' in author": accept

  loadstone:
    if: 
      - "'loadstone' in author": accept

  trymes:
    if:
      - "'TryMeS' in author and '720p' in title": accept

  lol:
    if:
      - "'-LOL' in title": accept
  eztv:
    if:
      - "'EZTV' in author":  accept

  ettv:
    if:
      - "'ettv' in author": accept
        
  vtv:
    if:
      - "'VTV' in author" : accept 

  bozx:
    if:
      - "'BOZX' in author" : accept

  commie:
    regexp:
      accept:
        - ^\[Commie\]    

  deadfish:
    regexp:
      accept:
        - ^\[DeadFish\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]

  anime-koi:
    regexp:
      accept:
        - ^\[Anime-Koi\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]

  underwater:
    regexp:
      accept:
        - ^\[Underwater\]
  otakumura:
    regexp:
      accept:
        - ^\[OtakuMura\]
  vivid:
    regexp:
      accept:
        - ^\[Vivid\]
  chihiro:
    regexp:
      accept:
        - ^\[Chihiro\]
      reject:
        - \.mp4  
        - \[480p\]
  chyuu:
    regexp:
      accept:
        - ^\[Chyuu\]
      reject:
        - \[480p\]

  fff:
    regexp:
      accept:
        - ^\[FFF

  gg:
    regexp:
      accept:
        - ^\[gg\]

  horrible-manga:
    regexp:
      accept:
        - ^\[HorribleScans\]
        
  horrible:
    regexp:
      accept:
        - ^\[HorribleSubs\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]

tasks:

  akagami:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=Shirayuki
    template:
      - defaults
      - horrible


  orange:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=orange
    template:
      - defaults
      - horrible
      
  Kouhosei:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=kouhosei
    template:
      - defaults
      - gg

  asterisk:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=asterisk
    template:
      - defaults
      - horrible

  seisen:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=seisen
    template:
      - defaults
      - horrible

  sousei:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=sousei
    template:
      - defaults
      - horrible

  rezero:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=re+zero+kara
    template:
      - defaults
      - horrible


  hundred:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=hundred
    template:
      - defaults
      - horrible

      
  dragonball:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=dragon+ball
    template:
      - defaults
      - deadfish

  Kuromukuro:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=kuromukuro
    template:
      - defaults
      - gg

  taimadou:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=taimadou
    template:
      - defaults
      - horrible

  kiznaiever:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=kiznaiver
    template:
      - defaults
      - horrible

  new-gate-manga:
    rss: http://www.nyaa.se/?page=rss&cats=2_12&term=new+gate
    template:
      - defaults
    accept_all: yes

  gate-manga:
    rss: http://www.nyaa.se/?page=rss&cats=2_12&term=gate+jsdf
    template:
      - default
    accept_all: yes
    
  titan-manga:
    rss: http://www.nyaa.se/?page=rss&cats=2_12&term=attack+on
    template:
      - defaults
      - horrible-manga
    
#  Psytrance-kat:
#    rss: http://kat.cr/usearch/psytrance/?rss=1&categoires[]=music
#    template:
#      - music
#    accept_all: yes

#  x-files:
#    rss: http://kat.cr/usearch/x%20files%20category%3Atv/?rss=1
#    template:
#      - ettv 
#      - defaults

#  real-time:
#    rss: http://kat.cr/usearch/real%20time%20category%3Atv/?rss=1
#    template: 
#      - defaults
#      - vtv

#  last-week-tonight:
#    rss: http://kat.cr/usearch/Last%20Week%20Tonight/?rss=1
#    template:
#      - defaults
#      - vtv

#  weeklywipe:
#    rss: http://kat.cr/usearch/weekly%20wipe/?rss=1
#    template:
#      - defaults
#      - eztv

