

templates:

  youtube:
    accept_all: yes
    exec:
      on_output:
        for_accepted: youtube-dl "{{url}}"
    notify:
      task:
        via:
          - toast: yes

  defaults:
    notify:
      task:
        via:
          - toast: yes
    transmission:
      host: 10.0.3.200
      port: 80
      path: /mnt/storage/contents/downloads
      ratio: 10

  aviguy:
    if:
      - "'AVIGUY' in author": accept

  loadstone:
    if:
      - "'loadstone' in author": accept

  trymes:
    if:
      - "'TryMeS' in author and '720p' in title": accept

  lol:
    if:
      - "'-LOL' in title": accept
  eztv:
    if:
      - "'EZTV' in author":  accept

  ettv:
    if:
      - "'ettv' in author": accept

  vtv:
    if:
      - "'VTV' in author" : accept

  bozx:
    if:
      - "'BOZX' in author" : accept

  
  commie:
    regexp:
      accept:
        - ^\[Commie\]

  bakedfish:
    regexp:
      accept:
        - ^\[BakedFish\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]
  deadfish:
    regexp:
      accept:
        - ^\[DeadFish\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]

  anime-koi:
    regexp:
      accept:
        - ^\[Anime-Koi\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]

  underwater:
    regexp:
      accept:
        - ^\[Underwater\]
  otakumura:
    regexp:
      accept:
        - ^\[OtakuMura\]
  vivid:
    regexp:
      accept:
        - ^\[Vivid\]
  chihiro:
    regexp:
      accept:
        - ^\[Chihiro\]
      reject:
        - \.mp4
        - \[480p\]
  chyuu:
    regexp:
      accept:
        - ^\[Chyuu\]
      reject:
        - \[480p\]

  fff:
    regexp:
      accept:
        - ^\[FFF

  gg:
    regexp:
      accept:
        - ^\[gg\]

  horrible-manga:
    regexp:
      accept:
        - ^\[HorribleScans\]

  horrible:
    regexp:
      accept:
        - ^\[HorribleSubs\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]



schedules:
  - tasks: 'animes-*'
    interval:
      hours: 1
  - tasks: 'tv'
    interval:
      hours: 1

tasks:

  tv:
    rss: http://showrss.info/user/153353.rss?magnets=true&namespaces=false&name=clean&quality=hd&re=no
    template:
      - defaults
    accept_all: yes
  
  animes-horrible:
    rss: https://nyaa.si/?page=rss&u=HorribleSubs
    template:
      - defaults
      - horrible

  animes-fate:
    rss: https://nyaa.si/?page=rss&u=Unlimited+Translation+Works
    template:
      - defaults
    regexp:
      accept:
        - Apocrypha
