templates:

  announce:
    exec: /home/jeff/bin/post.sh '{{title}}' '{{url}}'

  defaults:
    transmission:
      host: 127.0.0.1
      port: 9091
      ratio: 10
      username: transmission
      password: transmission
  aviguy:
    if:
      - "'AVIGUY' in author": accept

  loadstone:
    if:
      - "'loadstone' in author": accept

  trymes:
    if:
      - "'TryMeS' in author and '720p' in title": accept

  lol:
    if:
      - "'-LOL' in title": accept
  eztv:
    if:
      - "'EZTV' in author":  accept

  ettv:
    if:
      - "'ettv' in author": accept

  vtv:
    if:
      - "'VTV' in author" : accept

  bozx:
    if:
      - "'BOZX' in author" : accept

  kumo:
    regexp:
      accept:
        - Kumo
      reject:
        - sisters

  dank:
    regexp:
      accept:
        - Digital
      reject:
        - PNG4  
  commie:
    regexp:
      accept:
        - ^\[Commie\]

  bakedfish:
    regexp:
      accept:
        - ^\[BakedFish\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]
  deadfish:
    regexp:
      accept:
        - ^\[DeadFish\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]

  anime-koi:
    regexp:
      accept:
        - ^\[Anime-Koi\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]

  underwater:
    regexp:
      accept:
        - ^\[Underwater\]
  otakumura:
    regexp:
      accept:
        - ^\[OtakuMura\]
  vivid:
    regexp:
      accept:
        - ^\[Vivid\]
  chihiro:
    regexp:
      accept:
        - ^\[Chihiro\]
      reject:
        - \.mp4
        - \[480p\]
  chyuu:
    regexp:
      accept:
        - ^\[Chyuu\]
      reject:
        - \[480p\]

  fff:
    regexp:
      accept:
        - ^\[FFF

  gg:
    regexp:
      accept:
        - ^\[gg\]

  horrible-manga:
    regexp:
      accept:
        - ^\[HorribleScans\]

  horrible:
    regexp:
      accept:
        - ^\[SubsPlease\]
      reject:
        - \(400p\)
        - \(480p\)
        - \(1080p\)
        - \(360p\)

  erai:
    regexp:
      accept:
        - ^\[Erai-raws\]
      reject:
        - \[v0\]
        - 400p
        - 480p
        - 1080p
        - 360p
        - 540p
schedules:
  - tasks: 'animes-*'
    interval:
      hours: 1

tasks:

#  tv:
#    rss: http://showrss.info/user/153353.rss?magnets=true&namespaces=false&name=clean&quality=hd&re=no
#    template:
#      - defaults
#    accept_all: yes
  tv:
    rss: http://showrss.info/user/231825.rss?magnets=true&namespaces=false&name=clean&quality=hd&re=no
    template:
      - defaults
    accept_all: yes

  animes-erai:
    rss: https://nyaa.si/?page=rss&u=Erai-raws
    template:
      - defaults
      - erai

  animes-subs:
    rss: https://nyaa.si/?page=rss&u=subsplease
    template:
      - defaults
      - horrible
      - announce

  anime-cbz:
    rss: https://nyaa.si/?page=rss&u=danke
    template:
      - defaults
      - dank

  anime-kumo:
    rss: https://nyaa.si/?page=rss&u=aumakua
    template:
      - defaults
      - kumo
