

templates:

  defaults:
    transmission:
      host: 10.0.3.200
      port: 80
      path: /mnt/storage/contents/downloads
      ratio: 10

  aviguy:
    if:
      - "'AVIGUY' in author": accept

  loadstone:
    if:
      - "'loadstone' in author": accept

  trymes:
    if:
      - "'TryMeS' in author and '720p' in title": accept

  lol:
    if:
      - "'-LOL' in title": accept
  eztv:
    if:
      - "'EZTV' in author":  accept

  ettv:
    if:
      - "'ettv' in author": accept

  vtv:
    if:
      - "'VTV' in author" : accept

  bozx:
    if:
      - "'BOZX' in author" : accept

  commie:
    regexp:
      accept:
        - ^\[Commie\]

  bakedfish:
    regexp:
      accept:
        - ^\[BakedFish\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]
  deadfish:
    regexp:
      accept:
        - ^\[DeadFish\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]

  anime-koi:
    regexp:
      accept:
        - ^\[Anime-Koi\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]

  underwater:
    regexp:
      accept:
        - ^\[Underwater\]
  otakumura:
    regexp:
      accept:
        - ^\[OtakuMura\]
  vivid:
    regexp:
      accept:
        - ^\[Vivid\]
  chihiro:
    regexp:
      accept:
        - ^\[Chihiro\]
      reject:
        - \.mp4
        - \[480p\]
  chyuu:
    regexp:
      accept:
        - ^\[Chyuu\]
      reject:
        - \[480p\]

  fff:
    regexp:
      accept:
        - ^\[FFF

  gg:
    regexp:
      accept:
        - ^\[gg\]

  horrible-manga:
    regexp:
      accept:
        - ^\[HorribleScans\]

  horrible:
    regexp:
      accept:
        - ^\[HorribleSubs\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]



tasks:

  00_i2pmirror:
    from_transmission:
      host: 10.0.3.200
      port: 80
      onlycomplete: no
    template:
      - horrible
    exec:
      on_output:
        for_accepted: /home/jeff/git/dotfiles/flexget/anodex.sh '{{transmission_downloadDir}}/{{title}}' '{{title}}' '{{url}}'
  asterisk:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=asterisk
    template:
      - defaults
      - horrible

  izetta:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=Shuumatsu+no+Izetta
    template:
      - defaults
      - horrible

  sousei:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=sousei
    template:
      - defaults
      - horrible

  berserk:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=berserk
    template:
      - defaults
      - horrible

  gundam-iron:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=Iron-Blooded
    template:
      - defaults
      - horrible

  Keikaku:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=Keikaku
    template:
      - defaults
      - horrible

  bloodivores:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=bloodivores
    template:
      - defaults
      - horrible

  Kuromukuro:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=brave+witches
    template:
      - defaults
      - horrible

  taimadou:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=taimadou
    template:
      - defaults
      - horrible

  sekai-ni:
    rss: http://www.nyaa.se/?page=rss&cats=1_37&term=Sekai+ni
    template:
      - defaults
      - horrible

  ao-no-exorcist:
    rss: http://www.nyaa.se/?page=rss&cats=1_47&term=ao+no+exorcist
    template:
      - defaults
      - horrible

  new-gate-manga:
    rss: http://www.nyaa.se/?page=rss&cats=2_12&term=new+gate
    template:
      - defaults
    accept_all: yes

  gate-manga:
    rss: http://www.nyaa.se/?page=rss&cats=2_12&term=gate+jsdf
    template:
      - defaults
    accept_all: yes

  titan-manga:
    rss: http://www.nyaa.se/?page=rss&cats=2_12&term=attack+on
    template:
      - defaults
      - horrible-manga
