

templates:

  defaults:
    transmission:
      host: 10.0.3.200
      port: 80
      path: /mnt/storage/contents/downloads
      ratio: 10

  aviguy:
    if:
      - "'AVIGUY' in author": accept

  loadstone:
    if:
      - "'loadstone' in author": accept

  trymes:
    if:
      - "'TryMeS' in author and '720p' in title": accept

  lol:
    if:
      - "'-LOL' in title": accept
  eztv:
    if:
      - "'EZTV' in author":  accept

  ettv:
    if:
      - "'ettv' in author": accept

  vtv:
    if:
      - "'VTV' in author" : accept

  bozx:
    if:
      - "'BOZX' in author" : accept

  commie:
    regexp:
      accept:
        - ^\[Commie\]

  bakedfish:
    regexp:
      accept:
        - ^\[BakedFish\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]
  deadfish:
    regexp:
      accept:
        - ^\[DeadFish\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]

  anime-koi:
    regexp:
      accept:
        - ^\[Anime-Koi\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]

  underwater:
    regexp:
      accept:
        - ^\[Underwater\]
  otakumura:
    regexp:
      accept:
        - ^\[OtakuMura\]
  vivid:
    regexp:
      accept:
        - ^\[Vivid\]
  chihiro:
    regexp:
      accept:
        - ^\[Chihiro\]
      reject:
        - \.mp4
        - \[480p\]
  chyuu:
    regexp:
      accept:
        - ^\[Chyuu\]
      reject:
        - \[480p\]

  fff:
    regexp:
      accept:
        - ^\[FFF

  gg:
    regexp:
      accept:
        - ^\[gg\]

  horrible-manga:
    regexp:
      accept:
        - ^\[HorribleScans\]

  horrible:
    regexp:
      accept:
        - ^\[HorribleSubs\]
      reject:
        - \[400p\]
        - \[480p\]
        - \[1080p\]
        - \[360p\]



tasks:
  animes:
    rss: https://nyaa.si/?page=rss&u=HorribleSubs
    template:
      - defaults
      - horrible
        
  fate:
    rss: https://nyaa.si/?page=rss&u=Unlimited+Translation+Works
    template:
      - defaults
    regexp:
      accept:
        - Apocrypha

  #shitemasuka:
  #  rss: http://www.nyaa.se/?page=rss&cats=1_37&term=shitemasu+ka
  #  template:
  #    - defaults
  #    - horrible

  #titan:
  #  rss: http://www.nyaa.se/?page=rss&cats=1_37&term=Shingeki+no+Kyojin
  #  template:
  #    - defaults
  #    - horrible

  #sekaisuru:
  #  rss: http://www.nyaa.se/?page=rss&cats=1_37&term=Seikaisuru+Kado
  #  template:
  #    - defaults
  #    - horrible

  #clockwork:
  #  rss: http://www.nyaa.se/?page=rss&cats=1_37&term=clockwork
  #  template:
  #    - defaults
  #    - horrible

  #Rokudenashi:
  #  rss: http://www.nyaa.se/?page=rss&cats=1_37&term=Rokudenashi
  #  template:
  #    - defaults
  #    - horrible

  #zero-kara:
  #  rss: http://www.nyaa.se/?page=rss&cats=1_37&term=hajimeru+no+sho
  #  template:
  #    - defaults
  #    - horrible

  #asterisk:
  #  rss: http://www.nyaa.se/?page=rss&cats=1_37&term=asterisk
  #  template:
  #    - defaults
  #    - horrible

  #SwordOratoria:
  #  rss: http://www.nyaa.se/?page=rss&cats=1_37&term=sword+oratoria
  #  template:
  #    - defaults
  #    - horrible


  #berserk:
  #  rss: http://www.nyaa.se/?page=rss&cats=1_37&term=berserk
  #  template:
  #    - defaults
  #    - horrible

  #Keikaku:
  #  rss: http://www.nyaa.se/?page=rss&cats=1_37&term=Keikaku
  #  template:
  #    - defaults
  #    - horrible

